CREATE TABLE GER_TEMPO_LOGIN
(
 COD_EMP         NUMERIC(3,0) NOT NULL,
 COD_UNIDADE     NUMERIC(4,0) NOT NULL,
 NUM_EQUIPAMENTO NUMERIC(4,0) NOT NULL,
 COD_USUARIO     NUMERIC(8,0) NOT NULL,
 HORA_INICIAL    TIMESTAMP NOT NULL,
 HORA_FINAL      TIMESTAMP,
 TEMPO_LOGIN     NUMERIC(15,0), /* em minutos */
 TEMPO_FORMATADO VARCHAR(10),
 CONSTRAINT GER_TEMPO_LOGIN_PK PRIMARY KEY (COD_EMP,COD_UNIDADE,NUM_EQUIPAMENTO,COD_USUARIO,HORA_INICIAL)
)