COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */

CREATE PROCEDURE "REL_PGTO_CLI_FAIXAS_SP" 
(
  "ICOD_EMP" NUMERIC(3, 0),
  "ICOD_UNIDADE" NUMERIC(4, 0),
  "ICOD_CLIENTE_INICIAL" NUMERIC(14, 0),
  "ICOD_CLIENTE_FINAL" NUMERIC(14, 0),
  "IDTA_INICIAL" DATE,
  "IDTA_FINAL" DATE,
  "INUM_EQUIPAMENTO_INICIAL" NUMERIC(2, 0),
  "INUM_EQUIPAMENTO_FINAL" NUMERIC(2, 0),
  "ICOD_UNI_CLI" NUMERIC(3, 0),
  "ICOD_FUNC_INI" NUMERIC(4, 0),
  "ICOD_FUNC_FIM" NUMERIC(4, 0),
  "IFAIXA" NUMERIC(1, 0),
  "ITIPCONTRATO" NUMERIC(1, 0)
)
RETURNS
(
  "IDES_NOME" VARCHAR(50),
  "ICOD_CLIENTE" NUMERIC(14, 0),
  "IDTA_MOVIMENTO" DATE,
  "ICOD_CONTRATO" NUMERIC(11, 0),
  "IDTA_VENCIMENTO" DATE,
  "IVLR_PRESTACAO" NUMERIC(15, 2),
  "IFUNC_RECEBIMENTO" NUMERIC(4, 0),
  "INUM_PARCELA" NUMERIC(3, 0),
  "ICOD_UNI_CAD" NUMERIC(4, 0),
  "INUMFAIXA" NUMERIC(1, 0),
  "IDESFAIXA" VARCHAR(50),
  "ICONTRATO" VARCHAR(3)
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE "REL_PGTO_CLI_FAIXAS_SP" 
(
  "ICOD_EMP" NUMERIC(3, 0),
  "ICOD_UNIDADE" NUMERIC(4, 0),
  "ICOD_CLIENTE_INICIAL" NUMERIC(14, 0),
  "ICOD_CLIENTE_FINAL" NUMERIC(14, 0),
  "IDTA_INICIAL" DATE,
  "IDTA_FINAL" DATE,
  "INUM_EQUIPAMENTO_INICIAL" NUMERIC(2, 0),
  "INUM_EQUIPAMENTO_FINAL" NUMERIC(2, 0),
  "ICOD_UNI_CLI" NUMERIC(3, 0),
  "ICOD_FUNC_INI" NUMERIC(4, 0),
  "ICOD_FUNC_FIM" NUMERIC(4, 0),
  "IFAIXA" NUMERIC(1, 0),
  "ITIPCONTRATO" NUMERIC(1, 0)
)
RETURNS
(
  "IDES_NOME" VARCHAR(50),
  "ICOD_CLIENTE" NUMERIC(14, 0),
  "IDTA_MOVIMENTO" DATE,
  "ICOD_CONTRATO" NUMERIC(11, 0),
  "IDTA_VENCIMENTO" DATE,
  "IVLR_PRESTACAO" NUMERIC(15, 2),
  "IFUNC_RECEBIMENTO" NUMERIC(4, 0),
  "INUM_PARCELA" NUMERIC(3, 0),
  "ICOD_UNI_CAD" NUMERIC(4, 0),
  "INUMFAIXA" NUMERIC(1, 0),
  "IDESFAIXA" VARCHAR(50),
  "ICONTRATO" VARCHAR(3)
)
AS
DECLARE VARIABLE CONTRATO_CPP VARCHAR(3);
DECLARE VARIABLE CONTRATO_CRE VARCHAR(3);
BEGIN
  /* 1= LP, 2=PRÃ‰ LP, 3=ResÃ­duo, 4=PA, 5=Preventiva, 6=Pagamento Ant, 7=Pag outras redes, 0=TODAS  */
  /* 1=CRE, 2=CPP, 0=TODOS */
  IF (ITIPCONTRATO = 0) THEN
  BEGIN
       CONTRATO_CRE = 'CRE';
       CONTRATO_CPP = 'CPP';
  END
  ELSE IF (ITIPCONTRATO = 1) THEN
  BEGIN
	CONTRATO_CRE = 'CRE';
	CONTRATO_CPP = 'CRE';
  END
  ELSE IF (ITIPCONTRATO = 2) THEN
  BEGIN
       CONTRATO_CRE = 'CPP';
       CONTRATO_CPP = 'CPP';
  END
  IF ((IFAIXA = 1) OR (IFAIXA = 0)) THEN
	BEGIN
	FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
	       B.DES_CLIENTE,B.COD_UNIDADE, '1' AS NUMFAIXA, 'LP - LUCROS E PERDAS' AS DESFAIXA,A.COD_COMPL
	  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
								      A.COD_CLIENTE = B.COD_CLIENTE))
	 WHERE (A.COD_EMP=:ICOD_EMP)AND
	       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
	       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
	       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
	       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
	       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
	       ((A.DTA_MOVIMENTO - A.DTA_VENCIMENTO) > 0) AND
	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) >= 7) AND
	       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
	       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
	       (B.DES_CLIENTE IS NOT NULL)
	 ORDER BY 10, 8, 4, 3
	 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
	      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
   IF ((IFAIXA = 2) OR (IFAIXA = 0)) THEN
	   BEGIN
	   FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
		       B.DES_CLIENTE,B.COD_UNIDADE, '2' AS NUMFAIXA, 'PRÃ‰ LP - PRÃ‰ LUCROS E PERDAS' AS DESFAIXA,A.COD_COMPL
		  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
									      A.COD_CLIENTE = B.COD_CLIENTE))
		 WHERE (A.COD_EMP=:ICOD_EMP)AND
		       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
		       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
		       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
		       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
		       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
		       ((A.DTA_MOVIMENTO - A.DTA_VENCIMENTO) > 0) AND
	       	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) = 6) AND
		       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
		       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
		       (B.DES_CLIENTE IS NOT NULL)
		 ORDER BY 10, 8, 4, 3
		 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
		      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
   IF ((IFAIXA = 3) OR (IFAIXA = 0)) THEN
	   BEGIN
	   FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
		       B.DES_CLIENTE,B.COD_UNIDADE, '3' AS NUMFAIXA, 'RESÃDUO' AS DESFAIXA,A.COD_COMPL
		  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
									      A.COD_CLIENTE = B.COD_CLIENTE))
		 WHERE (A.COD_EMP=:ICOD_EMP)AND
		       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
		       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
		       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
		       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
		       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
		       ((A.DTA_MOVIMENTO - A.DTA_VENCIMENTO) > 0) AND
	       	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) <= 5) AND
	       	        ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) >= 2) AND
		       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
		       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
		       (B.DES_CLIENTE IS NOT NULL)
		 ORDER BY 10, 8, 4, 3
		 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
		      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
   IF ((IFAIXA = 4) OR (IFAIXA = 0)) THEN
	BEGIN
	   FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
		       B.DES_CLIENTE,B.COD_UNIDADE, '4' AS NUMFAIXA, 'PA - PERIODO DE ALERTA' AS DESFAIXA,A.COD_COMPL
		  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
									      A.COD_CLIENTE = B.COD_CLIENTE))
		 WHERE (A.COD_EMP=:ICOD_EMP)AND
		       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
		       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
		       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
		       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
		       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
		       ((A.DTA_MOVIMENTO - A.DTA_VENCIMENTO) > 0) AND
	       	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) = 1) AND
		       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
		       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
		       (B.DES_CLIENTE IS NOT NULL)
		 ORDER BY 10, 8, 4, 3
		 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
		      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
   IF ((IFAIXA = 5) OR (IFAIXA = 0)) THEN
	BEGIN
	   FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
		       B.DES_CLIENTE,B.COD_UNIDADE, '5' AS NUMFAIXA, 'PREVENTIVA' AS DESFAIXA,A.COD_COMPL
		  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
									      A.COD_CLIENTE = B.COD_CLIENTE))
		 WHERE (A.COD_EMP=:ICOD_EMP)AND
		       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
		       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
		       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
		       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
		       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
	       	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) = 0) AND
		       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
		       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
		       (B.DES_CLIENTE IS NOT NULL)
		 ORDER BY 10, 8, 4, 3
		 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
		      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
   IF ((IFAIXA = 6) OR (IFAIXA = 0)) THEN
	BEGIN
	  FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
	       B.DES_CLIENTE,B.COD_UNIDADE, '6' AS NUMFAIXA, 'PAGAMENTO ANTECIPADO' AS DESFAIXA,A.COD_COMPL
	  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
								      A.COD_CLIENTE = B.COD_CLIENTE))
	 WHERE (A.COD_EMP=:ICOD_EMP)AND
	       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
	       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
	       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
	       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
	       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
	       ((A.DTA_MOVIMENTO - A.DTA_VENCIMENTO) < 0) AND
	       ((SELECT SDIF_MES FROM RETORNA_MES_SP(A.DTA_VENCIMENTO,A.DTA_MOVIMENTO)) >= 1) AND
	       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP) AND
	       (B.COD_UNIDADE = :ICOD_UNIDADE) AND
	       (B.DES_CLIENTE IS NOT NULL)
	 ORDER BY 10, 8, 4, 3
	 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
	      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	   BEGIN
	      IF (ICOD_UNI_CLI = 9999) THEN
	   SUSPEND;
	      ELSE
	 IF ((ICOD_UNI_CLI = 0) AND
	    (ICOD_UNI_CAD IS NULL)) THEN
	     SUSPEND;
	   END
   END
   IF ((IFAIXA = 7) OR (IFAIXA = 0)) THEN
	BEGIN
	   FOR SELECT A.COD_CLIENTE,A.DTA_MOVIMENTO,A.COD_CONTRATO,A.DTA_VENCIMENTO,A.VLR_PRESTACAO,A.COD_TIPO_RECBTO,A.NUM_PARCELA,
		       B.DES_CLIENTE,B.COD_UNIDADE, '7' AS NUMFAIXA, 'PAGAMENTO DE OUTRAS REDES E LOJAS' AS DESFAIXA,A.COD_COMPL
		  FROM (CRE_RECEBIMENTOS A LEFT OUTER JOIN CRE_CLIENTES B ON( A.COD_EMP = B.COD_EMP AND
									      A.COD_CLIENTE = B.COD_CLIENTE))
		 WHERE (A.COD_EMP=:ICOD_EMP)AND
		       (A.COD_UNIDADE=:ICOD_UNIDADE)AND
		       (A.COD_CLIENTE BETWEEN :ICOD_CLIENTE_INICIAL AND :ICOD_CLIENTE_FINAL)AND
		       (A.DTA_MOVIMENTO BETWEEN :IDTA_INICIAL AND :IDTA_FINAL)AND
		       (A.NUM_EQUIPAMENTO BETWEEN :INUM_EQUIPAMENTO_INICIAL AND :INUM_EQUIPAMENTO_FINAL)AND
		       (A.COD_TIPO_RECBTO BETWEEN :ICOD_FUNC_INI AND :ICOD_FUNC_FIM) AND
		       (B.DES_CLIENTE IS NULL OR B.COD_UNIDADE <> :ICOD_UNIDADE) AND
		       (A.COD_COMPL = :CONTRATO_CRE OR A.COD_COMPL = :CONTRATO_CPP)
		 ORDER BY 10, 8, 4, 3
		 INTO ICOD_CLIENTE,IDTA_MOVIMENTO,ICOD_CONTRATO,IDTA_VENCIMENTO,IVLR_PRESTACAO,IFUNC_RECEBIMENTO,
		      INUM_PARCELA,IDES_NOME,ICOD_UNI_CAD,INUMFAIXA,IDESFAIXA,ICONTRATO DO
	    BEGIN
		IF(IDES_NOME IS NULL)THEN
		BEGIN
		  IF(IFUNC_RECEBIMENTO = 509)THEN
		     IDES_NOME = 'RECEBIMENTOS DIVERSOS';
		  ELSE
		    IF(IFUNC_RECEBIMENTO = 505)THEN
		       IDES_NOME = 'CLIENTE DE OUTRA REDE';
		    ELSE
		      IDES_NOME = 'CLIENTE DE OUTRA LOJA';
	       END
	       IF (ICOD_UNI_CLI = 9999) THEN
		   SUSPEND;
	       ELSE
		 IF ((ICOD_UNI_CLI = 0) AND
		    (ICOD_UNI_CAD IS NULL)) THEN
		     SUSPEND;
	    END
   END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;