COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */

CREATE PROCEDURE "REL_CLI_NEGATIVAR_SP" 
(
  "COD_EMP" NUMERIC(3, 0),
  "COD_UNIDADE" NUMERIC(4, 0),
  "DTA_NEG_INI" DATE,
  "DTA_NEG_FIM" DATE
)
RETURNS
(
  "WCOD_CLIENTE" NUMERIC(14, 0),
  "WDES_CLIENTE" VARCHAR(40),
  "WCNPJ_CPF" NUMERIC(14, 0),
  "WTIP_PESSOA" NUMERIC(1, 0),
  "WDTA_CADASTRO" DATE,
  "WCOD_UNIDADE" NUMERIC(4, 0),
  "WCONTRATO" NUMERIC(11, 0),
  "WDTA_VENDA" DATE,
  "WNUM_PARCELA" NUMERIC(3, 0),
  "WDTA_VENCIMENTO" DATE,
  "WVAL_PRESTACAO" NUMERIC(15, 2),
  "WTIP_PLANO_VP" VARCHAR(6),
  "WCOD_COMPL" VARCHAR(3),
  "WDES_FONE" VARCHAR(15),
  "WVLR_LIMITE" NUMERIC(15, 2),
  "WQTD_COMPRAS" NUMERIC(5, 0),
  "WSALDO" NUMERIC(15, 2),
  "WDTA_MAIOR_ATRASO" DATE,
  "WIND_SPC" NUMERIC(1, 0)
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE "REL_CLI_NEGATIVAR_SP" 
(
  "COD_EMP" NUMERIC(3, 0),
  "COD_UNIDADE" NUMERIC(4, 0),
  "DTA_NEG_INI" DATE,
  "DTA_NEG_FIM" DATE
)
RETURNS
(
  "WCOD_CLIENTE" NUMERIC(14, 0),
  "WDES_CLIENTE" VARCHAR(40),
  "WCNPJ_CPF" NUMERIC(14, 0),
  "WTIP_PESSOA" NUMERIC(1, 0),
  "WDTA_CADASTRO" DATE,
  "WCOD_UNIDADE" NUMERIC(4, 0),
  "WCONTRATO" NUMERIC(11, 0),
  "WDTA_VENDA" DATE,
  "WNUM_PARCELA" NUMERIC(3, 0),
  "WDTA_VENCIMENTO" DATE,
  "WVAL_PRESTACAO" NUMERIC(15, 2),
  "WTIP_PLANO_VP" VARCHAR(6),
  "WCOD_COMPL" VARCHAR(3),
  "WDES_FONE" VARCHAR(15),
  "WVLR_LIMITE" NUMERIC(15, 2),
  "WQTD_COMPRAS" NUMERIC(5, 0),
  "WSALDO" NUMERIC(15, 2),
  "WDTA_MAIOR_ATRASO" DATE,
  "WIND_SPC" NUMERIC(1, 0)
)
AS
DECLARE VARIABLE RETORNO NUMERIC(3);
BEGIN
      FOR SELECT A.COD_CLIENTE,
                 A.DES_CLIENTE,
                 A.NUM_CPF_CNPJ,
                 A.TIP_PESSOA,
                 A.DTA_CADASTRO,
                 B.COD_UNIDADE,
                 B.COD_CONTRATO,
                 B.DTA_VENDA,
                 B.NUM_PARCELA,
                 B.DTA_VENCIMENTO,
                 B.VLR_PRESTACAO,
                 B.TIP_PLANO_VP,
                 B.COD_COMPL
            FROM CRE_CLIENTES A,
                 CRE_CONTAS_RECEBER B
           WHERE A.COD_EMP = B.COD_EMP
             AND A.COD_CLIENTE = B.COD_CLIENTE
             AND A.COD_UNIDADE = :COD_UNIDADE
             AND B.IND_PRESTACAO = 0
             AND B.DTA_VENCIMENTO >= :DTA_NEG_INI
             AND B.DTA_VENCIMENTO <= :DTA_NEG_FIM
           ORDER BY A.DES_CLIENTE,B.COD_CONTRATO,B.DTA_VENCIMENTO,B.NUM_PARCELA
            INTO :WCOD_CLIENTE,:WDES_CLIENTE,:WCNPJ_CPF,
                 :WTIP_PESSOA,:WDTA_CADASTRO,:WCOD_UNIDADE,:WCONTRATO,
                 :WDTA_VENDA,:WNUM_PARCELA,:WDTA_VENCIMENTO,:WVAL_PRESTACAO,:WTIP_PLANO_VP,:WCOD_COMPL
        DO BEGIN
                 SELECT A.DES_FONE_RESID,
                 	A.VLR_LIMITE,
                        B.QTD_COMPRAS_VP,
                        B.VLR_SALDO,
                        B.DTA_MAIOR_ATRASO,
                        B.IND_SPC
                   FROM CRE_CLIENTES_CR A,
                        CRE_SALDOS_CLI B
                  WHERE A.COD_EMP = B.COD_EMP
                    AND A.COD_CLIENTE = B.COD_CLIENTE
                    AND A.COD_EMP = :COD_EMP
                    AND A.COD_CLIENTE = :WCOD_CLIENTE
                   INTO :WDES_FONE, :WVLR_LIMITE, :WQTD_COMPRAS, :WSALDO, :WDTA_MAIOR_ATRASO,:WIND_SPC;
                     IF (:WIND_SPC IS NULL) THEN WIND_SPC = 0;
                     IF (:WIND_SPC = 0) THEN
                     BEGIN
                        SUSPEND;
                     END
           END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;